#ifndef ATTRIBUTESANDSTATES_H
#define ATTRIBUTESANDSTATES_H

// ATTRIBUTES

#define WALKABLE 1
#define ATTACHED 2
#define CLIMBABLE 3
#define COLLIDEABLE 4
#define RIGID 5
#define ELASTIC 6
#define BOUNCY 7
#define PIERCING 8
#define HEALING 9
#define PLAYER_CONTROLLED 10
#define COLLECTIBLE 11
#define MYSTERIOUS 12
#define FLYABLE 13
#define FORCING 14

// STATES

#define UNDEFINED_STATE 0
#define FREE_FALLING 1
#define ON_A_SURFACE 2
#define WALKING 3
#define RUNNING 4
#define JUMPING 5
#define CLIMBING 6
#define FLYING 7

// MOVE COMMANDS

#define LEFT 1
#define RIGHT 3
#define UP 7
#define DOWN 15
#define UP_LEFT 8
#define UP_RIGHT 10
#define DOWN_LEFT 16
#define DOWN_RIGHT 18

// OTHER ACTIONS

#define IDLE 0
#define THROW 1
#define THROW_AUTO_RELEASE 2

// PHYSICAL CONSTANTS OF THE GAME WORLD (the result of trial and error)

#define GRAVITY 0.0004
#define ACCELERATION_CONSTANT 0.0004
#define SPEED_CONSTANT 0.13
#define MASS_CONSTANT 100.0
#define STATIC_FRICTION_COEFFICIENT 56.0
#define KINETIC_FRICTION_COEFFICIENT 4.0
#define BOUNCE_COEFFICIENT 0.2
#define ATTACHMENT_STRENGTH_CONSTANT 1.0

// PHYSICS PACKET INDEXES

#define MASS 0
#define VELOCITY_X 1
#define VELOCITY_Y 2
#define SURFACE_FRICTION 3

// COLLECTIBLE SYMBOLS

#define GRENADE_SYMBOL 1
#define DRONE_SYMBOL 2
#define SURROGATE_SYMBOL 3

#endif // ATTRIBUTESANDSTATES_H
